const CITY_ALIASES: Record<string, string> = {
  // New York boroughs and common metro-area labels are one city filter.
  'new york city': 'New York',
  'new york': 'New York',
  'new york, ny': 'New York',
  nyc: 'New York',
  brooklyn: 'New York',
  'brooklyn borough': 'New York',
  'brooklyn, ny': 'New York',
  manhattan: 'New York',
  'manhattan, ny': 'New York',
  queens: 'New York',
  'queens borough': 'New York',
  'queens, ny': 'New York',
  bronx: 'New York',
  'the bronx': 'New York',
  'bronx, ny': 'New York',
  'staten island': 'New York',
  'staten island, ny': 'New York',

  // Other common city variants.
  'los angeles': 'Los Angeles',
  la: 'Los Angeles',
  hollywood: 'Los Angeles',
  'west hollywood': 'Los Angeles',
  'washington dc': 'Washington',
  'washington d.c.': 'Washington',
  'washington, dc': 'Washington',
  'district of columbia': 'Washington',
  'city of london': 'London',
  brixton: 'London',
  camden: 'London',
  greenwich: 'London',
  hackney: 'London',
  hammersmith: 'London',
  islington: 'London',
  lambeth: 'London',
  southwark: 'London',
  'tower hamlets': 'London',
  wandsworth: 'London',
  westminster: 'London',
  wembley: 'London',
  'wembley park': 'London',

  // Venue-style values that Ticketmaster sometimes sends as the city.
  'auckland town hall': 'Auckland',
  'north head sanctuary': 'Auckland',
  nzicc: 'Auckland',
  'sidney myer music bowl': 'Melbourne',
  'town hall': 'Christchurch',
  'yas island': 'Abu Dhabi',

  // Accent-insensitive canonical labels used across regional feeds.
  brasilia: 'Brasília',
  'sao paulo': 'São Paulo',
  'sao caetano do sul': 'São Caetano do Sul',
  'sao jose do rio preto': 'São José do Rio Preto',
  'ribeirao preto': 'Ribeirão Preto',
  gdansk: 'Gdańsk',
  krakow: 'Kraków',
  dusseldorf: 'Düsseldorf',
  istanbul: 'Istanbul',
  izmir: 'Izmir',
  kusadasi: 'Kuşadası',
  ayvalik: 'Ayvalık',
  cesme: 'Çeşme',
  datca: 'Datça',
  kas: 'Kaş',
};

// Legacy rows may contain only a venue name. These well-known venue mappings
// keep older records usable until the concert sync is run again with city data.
const LEGACY_VENUE_CITIES: Record<string, string> = {
  '713 music hall': 'Houston',
  'ameris bank amphitheatre': 'Alpharetta',
  'arizona financial theatre': 'Phoenix',
  'ascend amphitheater': 'Nashville',
  'at&t stadium': 'Arlington',
  'beacon theatre': 'New York',
  'bok center': 'Tulsa',
  'brooklyn paramount': 'New York',
  'caesars superdome': 'New Orleans',
  'chase field': 'Phoenix',
  'coca-cola roxy': 'Atlanta',
  'dos equis pavilion': 'Dallas',
  dpac: 'Durham',
  'enmarket arena': 'Savannah',
  'fenway park': 'Boston',
  'fox theatre detroit': 'Detroit',
  'gas south arena': 'Duluth',
  'gillette stadium': 'Foxborough',
  'grand sierra resort and casino': 'Reno',
  'greek theatre-u.c. berkeley': 'Berkeley',
  'h-e-b center at cedar park': 'Cedar Park',
  'heritage bank center': 'Cincinnati',
  'hertz arena': 'Estero',
  'hollywood palladium': 'Los Angeles',
  'keybank center': 'Buffalo',
  'live oak bank pavilion': 'Wilmington',
  'mohegan sun arena': 'Uncasville',
  'mountain america center': 'Salt Lake City',
  'mvp arena': 'Albany',
  'nationals park': 'Washington',
  'nationwide arena': 'Columbus',
  'nissan stadium': 'Nashville',
  'north island credit union amphitheatre': 'Chula Vista',
  'ohio expo center & state fair': 'Columbus',
  'old national centre': 'Indianapolis',
  'paycom center': 'Oklahoma City',
  'petco park': 'San Diego',
  'protective stadium': 'Birmingham',
  'rice-eccles stadium': 'Salt Lake City',
  'rose bowl': 'Pasadena',
  'rupp arena': 'Lexington',
  'sap center at san jose': 'San Jose',
  'simmons bank arena': 'North Little Rock',
  sphere: 'Las Vegas',
  'talking stick resort amphitheatre': 'Phoenix',
  'the andrew j brady music center': 'Cincinnati',
  "the cynthia woods mitchell pavilion sponsored by huntsman": 'The Woodlands',
  "the dome at america's center": 'St. Louis',
  'the met presented by highmark': 'Philadelphia',
  'the pavilion at toyota music factory': 'Irving',
  'the salt shed indoors (shed)': 'Chicago',
  'the st. augustine amphitheatre': 'St. Augustine',
  'the venue at thunder valley casino resort': 'Lincoln',
  'utah first credit union amphitheatre': 'West Valley City',
  'van andel arena': 'Grand Rapids',
  'viejas arena at aztec bowl san diego state university': 'San Diego',
  'wamu theater': 'Seattle',
  'washington-grizzly stadium': 'Missoula',
  'weidner field': 'Green Bay',
  'yaamava theater': 'Highland',
  'youtube theater': 'Inglewood',
  'albert hall': 'London',
  'ao arena': 'Manchester',
  'aviva studios - warehouse': 'Manchester',
  'barrowland ballroom': 'Glasgow',
  'bath forum': 'Bath',
  belfast: 'Belfast',
  'blackpool opera house': 'Blackpool',
  'bournemouth international centre': 'Bournemouth',
  'bp pulse live': 'Birmingham',
  'bramham park': 'Leeds',
  'bridgewater hall': 'Manchester',
  'bristol beacon': 'Bristol',
  'british airways arc': 'Crawley',
  'cambridge corn exchange': 'Cambridge',
  'cardiff castle': 'Cardiff',
  'co-op live': 'Manchester',
  'congress theatre': 'Eastbourne',
  'crystal palace bowl': 'London',
  daresbury: 'Warrington',
  'electric studios': 'London',
  'eventim apollo': 'London',
  'henham park': 'Beccles',
  'leeds first direct bank arena': 'Leeds',
  lighthouse: 'Poole',
  'liverpool philharmonic hall': 'Liverpool',
  'lulworth castle': 'Wareham',
  'm&s bank arena liverpool': 'Liverpool',
  'manchester academy': 'Manchester',
  'motorpoint arena nottingham': 'Nottingham',
  'new theatre oxford': 'Oxford',
  nx: 'London',
  'o2 academy birmingham': 'Birmingham',
  'o2 academy bristol': 'Bristol',
  'o2 academy brixton': 'London',
  'o2 academy glasgow': 'Glasgow',
  'o2 academy leeds': 'Leeds',
  'o2 apollo manchester': 'Manchester',
  'o2 institute birmingham': 'Birmingham',
  'o2 victoria warehouse manchester': 'Manchester',
  olympia: 'London',
  'ovo arena wembley': 'London',
  'ovo hydro': 'Glasgow',
  'portsmouth guildhall': 'Portsmouth',
  'preston park': 'Brighton',
  'richfield avenue': 'Reading',
  roundhouse: 'London',
  'royal albert hall': 'London',
  'royal concert hall nottingham': 'Nottingham',
  'royal highland showgrounds': 'Edinburgh',
  'sandringham estate': 'King’s Lynn',
  'scarborough open air theatre': 'Scarborough',
  'scottish gas murrayfield': 'Edinburgh',
  'sheffield city hall oval hall': 'Sheffield',
  'southend cliffs pavilion': 'Southend-on-Sea',
  'stockton globe': 'Stockton-on-Tees',
  'swansea building society arena': 'Swansea',
  'symphony hall': 'Birmingham',
  'the anvil': 'Basingstoke',
  'the brighton centre': 'Brighton',
  'the comedy store': 'Manchester',
  'the national bowl': 'Milton Keynes',
  'the o2': 'London',
  'the piece hall': 'Halifax',
  "the queen's hall": 'Edinburgh',
  'tottenham hotspur stadium': 'London',
  'usher hall': 'Edinburgh',
  'utilita arena birmingham': 'Birmingham',
  'utilita arena cardiff': 'Cardiff',
  'utilita arena newcastle': 'Newcastle upon Tyne',
  'utilita arena sheffield': 'Sheffield',
  'venue cymru theatre': 'Llandudno',
  'victoria park london': 'London',
  'wembley stadium': 'London',
  'york barbican': 'York',

  // Asia-Pacific and World legacy venue rows.
  'national stadium': 'Singapore',
  'marvel stadium': 'Melbourne',
  'suncorp stadium': 'Brisbane',
  'engie stadium': 'Sydney',
  'go media stadium': 'Auckland',
  'spark arena': 'Auckland',
  'allianz stadium': 'Sydney',
  'victoria park - ballarat': 'Ballarat',
  'foreshore park': 'Newcastle',
  'kawana sports precinct': 'Sunshine Coast',
  'the domain': 'Sydney',
  'accor stadium': 'Sydney',
  'riverstage': 'Brisbane',
  'perth hpc': 'Perth',
  'kings park': 'Perth',
  'the star theatre': 'Singapore',
  'singapore indoor stadium': 'Singapore',
  'the tivoli': 'Brisbane',
  'odeon theatre': 'Hobart',
  'the fortitude music hall': 'Brisbane',
  'hindley st music hall': 'Adelaide',
  'the powerhouse': 'Brisbane',
  'the barracks precinct, north head sanctuary': 'Sydney',
  'arts centre melbourne, sidney myer music bowl': 'Melbourne',
  'state theatre, sydney': 'Sydney',
  'great hall, auckland town hall': 'Auckland',
  'james hay theatre, town hall': 'Christchurch',

  // World legacy venue rows.
  'etihad live, yas island': 'Abu Dhabi',
  'sunbet arena time square': 'Johannesburg',
  'grand arena at grandwest': 'Cape Town',
  'fnb stadium': 'Johannesburg',
  'küçükçiftlik park': 'Istanbul',
  parkorman: 'Istanbul',
  'paribu art - ana sahne': 'Istanbul',
  'harbiye cemil topuzlu açıkhava tiyatrosu': 'Istanbul',
  'jj arena ataşehir': 'Istanbul',
  'cermodern': 'Ankara',
  'tarihi havagazı fabrikası': 'Izmir',
  'cloof wine estate': 'Cape Town',
  babylon: 'Istanbul',
  'maximum uniq open air': 'Istanbul',
  'if performance hall beşiktaş': 'Istanbul',
  'jolly joker mersin': 'Mersin',
  'ora arena': 'Istanbul',
  'blind istanbul': 'Istanbul',
  'the river cabin': 'Johannesburg',
  'life park': 'Istanbul',
  'çotanak spor kompleksi': 'Giresun',
  'altın güvercin amfi tiyatro (kuşadası avm)': 'Kuşadası',
  'marmaris amfi tiyatro': 'Marmaris',
  'datça open air theater': 'Datça',
  'bodrum antique theatre': 'Bodrum',
  'patara antik tiyatrosu': 'Kaş',
  'zelve - paşabağları ören yeri': 'Avanos',
  'aspendos antik tiyatro': 'Serik',
  'ataköy marina arena': 'Istanbul',
  'bursa kültür park open air theatre': 'Bursa',
  'paribu vadi açıkhava': 'Istanbul',
  'larena beach': 'Antalya',
  'park arena antalya – aktüel sahne': 'Antalya',
  'zorlu psm - turkcell sahnesi': 'Istanbul',
  'oran açık hava sahnesi': 'Ankara',
  'antalya open air': 'Antalya',
  'dorock xl': 'Istanbul',
  'kali beach yalıkavak': 'Bodrum',
  'ayvalık amphitheater': 'Ayvalık',
  'swissotel the bosphorus': 'Istanbul',
  'denizli açıkhava tiyatrosu': 'Denizli',
  'hayal kahvesi kocaeli': 'Kocaeli',
  'sponge pub kaleiçi': 'Antalya',
  'holly stone performance hall antalya': 'Antalya',
  'holly stone performance hall - alanya': 'Alanya',
  'altınoluk amphi theater': 'Edremit',
  'bornova ayfer feray open air theater': 'Izmir',
  'jolly joker kocaeli': 'Kocaeli',
  'sapanca kırkpınar açıkhava tiyatrosu': 'Sapanca',
  'if performance hall tepe prime': 'Ankara',
  'mask beach': 'Istanbul',
  'merkez park amfi tiyatro': 'Adana',
  'mersin büyükşehir belediyesi kongre merkezi': 'Mersin',
  'hayal kahvesi bahçeşehir': 'Istanbul',
  'müskebi etkinlik merkezi': 'Bodrum',
  'lider club': 'Istanbul',
  'izmir kültürpark open air theatre': 'Izmir',
  'jolly joker kıyı istanbul': 'Istanbul',
  'jolly joker kartal istmarina': 'Istanbul',
  'jolly joker vadistanbul': 'Istanbul',
  'kadıköy belediyesi selamiçeşme': 'Istanbul',
  'mawish beach & disco': 'Bodrum',
  'yalova barış manço openair theatre': 'Yalova',
  'büyükçekmece kültürpark kemal sunal amfi tiyatro': 'Istanbul',
  'bostanlı karşıyaka theatre': 'Izmir',
  'the sponge performance hall': 'Antalya',
  'çeşme open air theatre': 'Çeşme',
  'mustafa altunhan tesisleri': 'Edirne',
  'mkm attila ilhan hall': 'Istanbul',
  'club inferno bursa': 'Bursa',
  'candyland bodrum': 'Bodrum',
  'emmarentia dam': 'Johannesburg',
  'festival park yenikapı': 'Istanbul',
  'etimesgut bld. korkut ata kültür ve kongre merkezi açıkhava sahnesi': 'Ankara',
  'leb-i derya aksazlar': 'Fethiye',
  'if performance hall': 'Istanbul',
  'hayal kahvesi güre': 'Edremit',
  'bodrum herodot kültür merkezi': 'Bodrum',
  'didim amfi tiyatro': 'Didim',
  'antalya aktüel sahne': 'Antalya',
  'bornova aşık veysel açıkhava tiyatrosu': 'Izmir',
  'dreampark istanbul': 'Istanbul',
  'hayal kahvesi aqua florya': 'Istanbul',
  'metreküp bodrum': 'Bodrum',
  'new covent garden theatre': 'Johannesburg',

  // Europe
  'vinyl room - ziggo dome': 'Amsterdam',
  'ziggo dome': 'Amsterdam',
  'ziggo dome club': 'Amsterdam',
  'afas dome': 'Amsterdam',
  'afas live loge': 'Amsterdam',
  'sentrum scene': 'Oslo',
  'unity arena': 'Oslo',
  'telenor arena': 'Oslo',
  '3arena': 'Stockholm',
  'strawberry arena': 'Stockholm',
  'slottsskogen': 'Gothenburg',
  'veikkaus arena': 'Helsinki',
  suvilahti: 'Helsinki',
  'hallenstadion': 'Zurich',
  'arena im open air park': 'Gelsenkirchen',
  'wacken festivalgelände': 'Wacken',
  'tauron arena kraków': 'Kraków',
  'polsat plus arena gdańsk': 'Gdańsk',
  'estadi olímpic lluis companys': 'Barcelona',
  'olympiapark berlin': 'Berlin',
  'uber arena': 'Berlin',
  'tempodrom': 'Berlin',
  'mitschubishi electric halle': 'Düsseldorf',
  'mitsubishi electric halle': 'Düsseldorf',
  'olympiahalle': 'Munich',
  'barclays arena': 'Hamburg',
  'münchen olympiahalle': 'Munich',
  'atlas arena': 'Lodz',
  'unipol forum': 'Milan',
  'unipol arena': 'Bologna',
  'unipol dome': 'Bologna',
  'ippodromo snai san siro': 'Milan',
  'palau sant jordi': 'Barcelona',
  'sant jordi club': 'Barcelona',
  'palacio vistalegre': 'Madrid',
  'estadio riyadh air metropolitano': 'Madrid',
  'hallendstadion': 'Zurich',
  'wiener stadthalle - halle d': 'Vienna',
  'vorst nationaal/forest national': 'Brussels',
  'king baudouin stadium': 'Brussels',
  'stade roi boudoin - brussels': 'Brussels',
  'estadio shakira(iberdrola music)': 'Madrid',
  'pge narodowy': 'Warsaw',
  'ergo arena': 'Gdańsk',
  'movistar arena': 'Madrid',
  'croke park': 'Dublin',
  'ing arena': 'Liège',
  'auditorio starlite': 'Marbella',
  '3olympia theatre': 'Dublin',
  'cos torwar': 'Warsaw',
  'raiffeisen halle im gasometer': 'Vienna',
  'klub palladium': 'Warsaw',
  'alcatraz': 'Milan',
  'roig arena': 'Valencia',
  'zag arena': 'Hannover',
  'lotto arena antwerpen': 'Antwerp',
  'allas live': 'Tallinn',
  falconersalen: 'Copenhagen',
  'fiera del levante': 'Bari',
  'farmasi arena': 'Istanbul',
  'slane castle': 'Slane',
  'imma': 'Dublin',

  // Latino
  'foro red access': 'Mexico City',
  'classic hall': 'Recife',
  'palacio de bellas artes': 'Mexico City',
  'foro corona monterrey': 'Monterrey',
  'multiplan hall park shopping são caetano': 'São Caetano do Sul',
  'la maraka': 'Mexico City',
  'pepsi center': 'Mexico City',
  'tokio marine hall': 'São Paulo',
  'espaço unimed - avcb nº774465-alvará de funcionamento 2024/05734-00': 'São Paulo',
  'arena brb mané garrincha': 'Brasília',
  'auditorio banamex': 'Monterrey',
  'auditorio telmex': 'Guadalajara',
  'palacio de los deportes': 'Mexico City',
  'pabellón del palacio de los deportes': 'Mexico City',
  'auditorio nacional': 'Mexico City',
  'teatro metropolitan': 'Mexico City',
  'multiplan hall ribeirão shopping': 'Ribeirão Preto',
  'autódromo de interlagos': 'São Paulo',
  'teatro de la ciudad esperanza iris': 'Mexico City',
  'teatro estudio cavaret': 'Guadalajara',
  'escenario gnp seguros': 'Mexico City',
  'el lunario del auditorio nacional': 'Mexico City',
  'centro de formação olímpica': 'Fortaleza',
  'teatro diana (gdl)': 'Guadalajara',
  'auditorio bb': 'Mexico City',
  'conjunto de artes escenicas': 'Guadalajara',
  'autodromo hnos. rodriguez': 'Mexico City',
  'foro stelaris fiesta americana reforma': 'Mexico City',
  'arena opus': 'Curitiba',
  'pedreira paulo leminski': 'Curitiba',
  'foro puebla': 'Puebla',
  'estádio beira-rio': 'Porto Alegre',
  'casa de apostas arena fonte nova': 'Salvador',
  'teatro sergio magaña': 'Mexico City',
  'c3 stage gdl': 'Guadalajara',
  'café iguana': 'Monterrey',
  'marina park': 'Fortaleza',
  'garden eventos': 'Pato Branco',
  'jardines de méxico': 'Tequesquitengo',
  'black cap eventos': 'Mexico City',
  qualistage: 'Rio de Janeiro',
  'nenue test mty': 'Monterrey',
  'estadio gnp seguros': 'Mexico City',
  'expo santa fe': 'Mexico City',
  'vivo rio': 'Rio de Janeiro',
  'venue test 2': 'Mexico City',
  teste: 'Mexico City',
  novenue: 'Mexico City',
  'arena vfg': 'Guadalajara',
  'cidade do rock': 'Rio de Janeiro',
  'recinto de exposições alberto bertelli lucatto': 'São José do Rio Preto',
  'allianz parque': 'São Paulo',
  'estadio alfredo harp helú': 'Mexico City',
  'estadio borregos': 'Monterrey',
  morumbis: 'São Paulo',
  'coliseo gnp seguros': 'Mexico City',
  'mercado livre arena pacaembu': 'São Paulo',
  'suhai music hall': 'São Paulo',
  'befly hall': 'Belo Horizonte',
  'arena monterrey': 'Monterrey',
  'parque fundidora': 'Monterrey',
  'estadio bbva': 'Monterrey',
  'monumental plaza de toros méxico': 'Mexico City',
  'centro de convenciones tlatelolco': 'Mexico City',
  velodromo: 'São Paulo',
  audio: 'São Paulo',
  'cine lido': 'Mexico City',
  'campo marte': 'Mexico City',
  'circo voador': 'Rio de Janeiro',
  'live curitiba': 'Curitiba',
  hangar: 'São Paulo',
  'mister rock': 'Belo Horizonte',
  "tork n' roll": 'Curitiba',
  'estacionamento do jaraguá': 'São Paulo',
  'sala silvestre revueltas': 'Mexico City',
};

function cityKey(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

export function normalizeCityName(value: string | null | undefined): string | null {
  if (!value || !value.trim()) return null;
  const cleaned = value.replace(/\s+/g, ' ').trim();
  return CITY_ALIASES[cityKey(cleaned)] || cleaned;
}

function parseCityFromLocation(location: string): string | null {
  const parts = location.split(',').map((part) => part.trim()).filter(Boolean);
  if (parts.length < 2) return null;

  const last = parts[parts.length - 1];
  const candidate = /^[A-Za-z]{2,3}$/.test(last) ? parts[parts.length - 2] : last;
  return normalizeCityName(candidate);
}

export function resolveConcertCity(city: string | null | undefined, location: string | null | undefined): string | null {
  const storedCity = normalizeCityName(city);
  if (storedCity) return storedCity;

  if (!location || !location.trim()) return null;

  const normalizedLocationKey = cityKey(location);
  const legacyCity = Object.entries(LEGACY_VENUE_CITIES).find(
    ([venue]) => cityKey(venue) === normalizedLocationKey
  )?.[1];

  return legacyCity || parseCityFromLocation(location);
}
