name: News Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    # Dodajemo ovo da ućutkamo GitHub upozorenje
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Prebacili smo sa 20 na 24

      - name: Install dependencies
        run: |
          npm install
          npm install -g ts-node typescript @types/node

      - name: Run Fetch Script
        run: ts-node app/api/fetch-news/route.ts
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}